# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/setup-msbuild@v1.1
      - run: cl final.c
      - run: bash ./intermediate.sh *.txt

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: gcc final.c -o final
      - run: bash ./intermediate.sh *.txt
