# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  windows_bash:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - run: gcc final.c -o final
    - run: bash ./intermediate.sh *.txt
      shell: bash
    - run: ./final.exe *.txt
      shell: bash

  windows_pwsh:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - run: gcc final.c -o final
    - run: bash ./intermediate.sh *.txt
      shell: pwsh
    - run: ./final.exe *.txt
      shell: pwsh

  windows_cmd:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - run: gcc final.c -o final
    - run: bash ./intermediate.sh *.txt
      shell: cmd
    - run: ./final.exe *.txt
      shell: cmd
